version: '3.8'

services:
  sports-app:
    build: .
    container_name: sports-app
    network_mode: host
    volumes:
      - /opt/conf:/opt/conf
      - /opt/logs/sports:/app/logs
    environment:
      - TZ=Asia/Seoul
      - BASE_PATH=/app/data
      - LOG_HOME=/app/logs
    restart: unless-stopped