# actas
server.port=8021

# actas
server.servlet.session.cookie.name=sports_jsessionid

# actas
spring.datasource.hikari.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.jdbc-url=${sports_test_DB_URL}

spring.datasource.hikari.username=${sports_test_DB_USERNAME}
spring.datasource.hikari.password=${sports_test_DB_PASSWORD}
spring.datasource.hikari.maximum-pool-size = 3
spring.datasource.hikari.minimum-idle = 1
spring.datasource.hikari.maxLifetime = 1800000
spring.datasource.hikari.idle-timeout = 600000
spring.datasource.hikari.leak-detection-threshold=5000

# 1. ??? ?? ?? ?: ?? ??? ???? localhost(127.0.0.1)? ??
# 2. ?? ?? ?: docker-compose? environment ?? ???? my-redis(?????)? ??

#spring.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
#spring.redis.port=${SPRING_DATA_REDIS_PORT:6379}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=${REDIS_DATABASE_NUMBER}
spring.data.redis.connect-timeout=5000ms
spring.data.redis.timeout=5000ms




# 2.7 ?? ???? ?? ?? ? (?? ??)
#spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
#spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
#spring.data.redis.connect-timeout=5000ms
#spring.data.redis.timeout=5000ms

ncp_api_accessKey=${ncp_api_accessKey}
ncp_api_secretKey=${ncp_api_secretKey}
ncp_api_cwKey=${ncp_api_cwKey}
ncp_api_instanceNo=${ncp_api_instanceNo}
