spring.application.name=SPORTS MES 1.0
#spring.profiles.active=sports
spring.profiles.active=sports,ncp
mes.project-name=sports
# prod ? ??, local ????

server.address=0.0.0.0

server.forward-headers-strategy=framework
server.max-http-header-size=30000

# ÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂ«ÃÂÃÂÃÂÃÂ ÃÂÃÂ«ÃÂÃÂ¡ÃÂÃÂÃÂÃÂªÃÂÃÂ·ÃÂÃÂ¸ÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ ÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂªÃÂÃÂ°ÃÂÃÂ (60ÃÂÃÂ¬ÃÂÃÂ´ÃÂÃÂ, ÃÂÃÂªÃÂÃÂ¸ÃÂÃÂ°ÃÂÃÂ«ÃÂÃÂ³ÃÂÃÂ¸ÃÂÃÂ¬ÃÂÃÂÃÂÃÂ 1800(30ÃÂÃÂ«ÃÂÃÂ¶ÃÂÃÂ))
server.servlet.session.timeout=1800
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.path=/

server.servlet.context-path=/sports
spring.mvc.servlet.path=/
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.html
server.servlet.session.cookie.http-only=true

#spring.devtools.livereload.enabled=true
spring.web.locale=ko
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


server.error.include-exception=false
server.error.include-stacktrace=NEVER
server.error.whitelabel.enabled=true


spring.thymeleaf.prefix=classpath:templates/
spring.thymeleaf.suffix=.html
#spring.thymeleaf.mode=HTML
#spring.thymeleaf.encoding=UTF-8
#spring.thymeleaf.servlet.content-type=text/html

spring.thymeleaf.cache=false
#spring.thymeleaf.check-template-location=true

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.devtools.restart.enabled=false


#create: ÃÂÃÂªÃÂÃÂ¸ÃÂÃÂ°ÃÂÃÂ¬ÃÂÃÂ¡ÃÂÃÂ´ÃÂÃÂ­ÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ´ÃÂÃÂ«ÃÂÃÂ¸ÃÂÃÂ ÃÂÃÂ¬ÃÂÃÂÃÂÃÂ­ÃÂÃÂ¬ÃÂÃÂ ÃÂÃÂ ÃÂÃÂ­ÃÂÃÂÃÂÃÂ ÃÂÃÂ«ÃÂÃÂÃÂÃÂ¤ÃÂÃÂ¬ÃÂÃÂÃÂÃÂ ÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ± (DROP + CREATE)
#create-drop: createÃÂÃÂ¬ÃÂÃÂÃÂÃÂ ÃÂÃÂªÃÂÃÂ°ÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ¼ÃÂÃÂ«ÃÂÃÂÃÂÃÂ ÃÂÃÂ¬ÃÂÃÂ¢ÃÂÃÂÃÂÃÂ«ÃÂÃÂ£ÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂ ÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ ÃÂÃÂ­ÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ´ÃÂÃÂ«ÃÂÃÂ¸ÃÂÃÂ DROP
#update: ÃÂÃÂ«ÃÂÃÂ³ÃÂÃÂÃÂÃÂªÃÂÃÂ²ÃÂÃÂ½ÃÂÃÂ«ÃÂÃÂ¶ÃÂÃÂÃÂÃÂ«ÃÂÃÂ§ÃÂÃÂ ÃÂÃÂ«ÃÂÃÂ°ÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ(ÃÂÃÂ¬ÃÂÃÂÃÂÃÂ´ÃÂÃÂ¬ÃÂÃÂÃÂÃÂDBÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂ«ÃÂÃÂÃÂÃÂ ÃÂÃÂ¬ÃÂÃÂÃÂÃÂ¬ÃÂÃÂ¬ÃÂÃÂÃÂÃÂ©ÃÂÃÂ­ÃÂÃÂÃÂÃÂÃÂÃÂ«ÃÂÃÂ©ÃÂÃÂ´ ÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂ«ÃÂÃÂÃÂÃÂ¨)
#validate: ÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂ­ÃÂÃÂÃÂÃÂ°ÃÂÃÂ­ÃÂÃÂÃÂÃÂ°ÃÂÃÂ¬ÃÂÃÂÃÂÃÂ ÃÂÃÂ­ÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ´ÃÂÃÂ«ÃÂÃÂ¸ÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ´ ÃÂÃÂ¬ÃÂÃÂ ÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ ÃÂÃÂ«ÃÂÃÂ§ÃÂÃÂ¤ÃÂÃÂ­ÃÂÃÂÃÂÃÂÃÂÃÂ«ÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂ«ÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂ§ÃÂÃÂÃÂÃÂ«ÃÂÃÂ§ÃÂÃÂ ÃÂÃÂ­ÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ¸
#none: ÃÂÃÂ¬ÃÂÃÂÃÂÃÂ¬ÃÂÃÂ¬ÃÂÃÂÃÂÃÂ©ÃÂÃÂ­ÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂ§ÃÂÃÂ ÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ(ÃÂÃÂ¬ÃÂÃÂÃÂÃÂ¬ÃÂÃÂ¬ÃÂÃÂÃÂÃÂ¤ÃÂÃÂ¬ÃÂÃÂÃÂÃÂ ÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂ«ÃÂÃÂÃÂÃÂ ÃÂÃÂªÃÂÃÂ°ÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ´ÃÂÃÂ¬ÃÂÃÂ§ÃÂÃÂÃÂÃÂ«ÃÂÃÂ§ÃÂÃÂ ÃÂÃÂªÃÂÃÂ´ÃÂÃÂÃÂÃÂ«ÃÂÃÂ¡ÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ noneÃÂÃÂ¬ÃÂÃÂÃÂÃÂ´ÃÂÃÂ«ÃÂÃÂÃÂÃÂ¼ÃÂÃÂªÃÂÃÂ³ÃÂÃÂ  ÃÂÃÂ­ÃÂÃÂÃÂÃÂÃÂÃÂ«ÃÂÃÂÃÂÃÂ¤.)
spring.jpa.hibernate.ddl-auto=none

spring.data.jpa.repositories.enabled=true
spring.data.jdbc.repositories.enabled=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults= false
spring.jpa.open-in-view=false

#ÃÂÃÂ¬ÃÂÃÂ½ÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ SQLÃÂÃÂ¬ÃÂÃÂÃÂÃÂ ÃÂÃÂ«ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂªÃÂÃÂ¸ÃÂÃÂ° ÃÂÃÂ¬ÃÂÃÂ¢ÃÂÃÂÃÂÃÂªÃÂÃÂ²ÃÂÃÂ ÃÂÃÂ«ÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ¸ ÃÂÃÂªÃÂÃÂ²ÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ¸ÃÂÃÂ¬ÃÂÃÂ§ÃÂÃÂ
spring.jpa.properties.hibernate.format_sql=true
#ÃÂÃÂ¬ÃÂÃÂ½ÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ SQLÃÂÃÂ¬ÃÂÃÂÃÂÃÂ ÃÂÃÂ«ÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ¸ ÃÂÃÂªÃÂÃÂ²ÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ¸ÃÂÃÂ¬ÃÂÃÂ§ÃÂÃÂ
spring.jpa.properties.hibernate.show-sql=true
spring.jpa.properties.hibernate.use_sql_comments=false
#logging.level.org.hibernate=debug
logging.level.mes.config.RoutingDataSource=DEBUG
logging.level.org.hibernate=info
#spring.jpa.properties.hibernate.highlight_sql=true
#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.type.descriptor.sql=trace

#spring.session.jdbc.initialize-schema=always
spring.session.store-type=jdbc
spring.data.redis.repositories.enabled=false
spring.batch.jdbc.initialize-schema=never
spring.session.jdbc.initialize-schema=never
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.batch.BatchAutoConfiguration


# application.properties
#mybatis.type-aliases-package=mes.domain.model
#mybatis.type-handlers-package=mes.domain.typehandler
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.default-fetch-size=100
mybatis.configuration.default-statement-timeout=30

logging.level.root=info
logging.level.mes.app.PopBill=INFO
site=mes21
mqtt_host=10.10.10.231
mqtt_web_port=9001
hmi_topic=${site}_hmi_data


# =========================
# MES BASE / PROJECT PATH
# =========================
# OSÃÂÃÂ«ÃÂÃÂ³ÃÂÃÂ ÃÂÃÂªÃÂÃÂ¸ÃÂÃÂ°ÃÂÃÂ«ÃÂÃÂ³ÃÂÃÂ¸ ÃÂÃÂªÃÂÃÂ²ÃÂÃÂ½ÃÂÃÂ«ÃÂÃÂ¡ÃÂÃÂ
mes.base-path=${BASE_PATH}
mes.project-path=${mes.base-path}/${mes.project-name}

# =========================
# ÃÂÃÂ­ÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ¼ ÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂ¹ÃÂÃÂ
# =========================
mes_form_path=${mes.project-path}/mes_form

# =========================
# ÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂ«ÃÂÃÂ¡ÃÂÃÂÃÂÃÂ«ÃÂÃÂÃÂÃÂ ÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂ¹ÃÂÃÂ
# =========================
file_upload_path=${mes.project-path}

# =========================
# ÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ ÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂ«ÃÂÃÂ¡ÃÂÃÂÃÂÃÂ«ÃÂÃÂÃÂÃÂ
# =========================
file_temp_upload_path=${mes.project-path}/upload_temp

weather.api.endpoint=https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0

#mail
spring.mail.host=smtp.naver.com
spring.mail.port=465
spring.mail.username=actasshare@naver.com
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.default-encoding=UTF-8


popbill.linkId=ACTAS
popbill.isTest=true
popbill.isIpRestrictOnOff=true

openai.api.key=${OPENAI_API_KEY}

# ìì¦ëª¨ ë¼ì´ì ì¤ í¤(actascld.co.kr)
wizmo.license=actascld.co.kr,679493286538488#B0NsIOiwmbBJye0ICRiwiI34TQIVnWLNFMFFzLxMkMrIVTvZzd4ZFW7U6LKd4Tip5LIdHdmpmbThlShVzMr3WaSNUaxMzR7siVvp4LrhTMytUbWVUMjFGSaJjQ8k5bCFTN73GMZRVT4h4RO3CNp3WVwJmdth7VTd7MVxmQ74USPtWNxo5KLdmdrIkSZ3UYId4ND3mVWNjRDBlSLFTUiZFbhBDWrh4Swo5dtBFcxIHOQ36dRpHRL56VJRUa4tWWyVTdyMTZplFUYt6bpJUbkJkW6JUZS9WdvA5R5RHeFp4TNF4ZCBzQ5B7c7MzcxMzQQxGTwhFZstSRsNkczFkdh3WRZ9WVqRDaMpWTxlmeVVjaiZVSFhWeFV4M48GO5NHbkVFe8olUzd6Q8ZVQqF6TBZHT0JFNrg4cDhkcPplRad6UjhkVZN7UupkcKVGNQhlWBRne6t6KRJWbvc7SwlkV8h6dRhTNLNWVvMmI0IyUiwiIDZUQCZURwMjI0ICSiwSM9MTMwUTMwATM0IicfJye35XX3JSSwIjUiojIDJCLi86bpNnblRHeFBCI4VWZoNFelxmRg2Wbql6ViojIOJyes4nI5kkTRJiOiMkIsIibvl6cuVGd8VEIgIXZ7VWaWRncvBXZSBybtpWaXJiOi8kI1xSfis4N8gkI0IyQiwiIu3Waz9WZ4hXRgAydvJVa4xWdNBybtpWaXJiOi8kI1xSfiQjR6QkI0IyQiwiIu3Waz9WZ4hXRgACUBx4TgAybtpWaXJiOi8kI1xSfiMzQwIkI0IyQiwiIlJ7bDBybtpWaXJiOi8kI1xSfiUFO7EkI0IyQiwiIu3Waz9WZ4hXRgACdyFGaDxWYpNmbh9WaGBybtpWaXJiOi8kI1tlOiQmcQJCLiAzM6UTNwAyNyITM4IDMyIiOiQncDJCLiI7au26YuQGbjNXY4NWYiojIz5GRiwiIkqI1AOY1ReJ1iojIh94QiwiI8gDN8MTN6gjMzkDN9cjNiojIklkIs4XXbpjInxmZiwiIyYHMyAjMiojIyVmdiwSZzxWYmpjIhNYZ

douzone.caller-name=API_gcmsAmaranth39360
douzone.access-token=MmZAM19e3YQ6bcgpLOoTM5eYPNwvZ4
douzone.hash-key=17401456432566681283156322994419565648145379
douzone.base-url=https://erp.gst-e.com
douzone.group-seq=gcmsAmaranth39360
#barobill API service
barobill.testkey = C05B16DE-46F2-4F01-92C9-5346C3075CA2
barobill.certKey = 7503182E-4355-48C9-A1F4-B13840F49EB2

ncp.object-storage.endpoint=https://kr.object.ncloudstorage.com
ncp.object-storage.region=kr-standard
ncp.object-storage.access-key=${ncp_api_accessKey}
ncp.object-storage.secret-key=${ncp_api_secretKey}
ncp.object-storage.bucket=actas-ai-files